### ISSUE TITLE
Poll system

### ISSUE THREAD

**Issue by g1ronn1mo** [sib-swiss/training-collection#62]
Hey, 
how about implementing a poll system, where you are allowed to vote for site that you like? Btw. i found an awesome tutorial about using git: https://www.golinuxcloud.com/git-basics/ 

Best regards

Benedikt

**Comment by GeertvanGeest** [comment]
Hi Benedikt,

Thanks for the feedback. 

It's indeed challenging to find a 'high quality' or 'most-used' course in this list. In order to fix that we're currently implementing a web application (release planned before Christmas) in which you can filter/sort based on github stars (~community appreciation) and days since last push (~up-to-dateness). Would that be similar to what you are suggesting? 

Thanks for the website link, it looks like a very nice tutorial. However, it doesn't seem to have an associated git repository, which would be required for this list.. 

Bw,
Geert

**Comment by GeertvanGeest** [comment]
[glittr.org](https://glittr.org) is online now. Closing this.
